function make_stim_set(stim_set, fs, hrirs, kemar_fs, kemar_hrirs, target_directory, include_normal_orientation)
    arguments
        stim_set StimulusSet
        fs {mustBeNumeric}
        hrirs (:,360,:)
        kemar_fs {mustBeNumeric}
        kemar_hrirs (73,2,:)
        target_directory string
        include_normal_orientation = false
    end
    if exist(target_directory, "dir")
        error("Refusing to write stims to an existing directory");
    end
    mkdir(target_directory);
    manifest_file = setup_manifest_file(target_directory);
    ild_matched_orientation_map = get_ild_matched_orientation_map( ...
        stim_set, ...
        hrirs, ...
        kemar_fs, ...
        kemar_hrirs);
    for target_distance_cm = stim_set.target_distances_cm
        for slowdown_factor = stim_set.slowdowns
            for target_azimuth_deg = stim_set.azimuths_deg
                [ultrasound_pulse, click_pulse] = get_ultrasound_pulse_for_slowdown( ...
                    stim_set, slowdown_factor);
                kemar_stim = make_matched_kemar_stim( ...
                    kemar_hrirs, ...
                    kemar_fs, ...
                    ultrasound_pulse, ...
                    slowdown_factor, ...
                    target_distance_cm / 100, ...
                    target_azimuth_deg, ...
                    false);
                save_single_stim( ...
                    target_directory, ...
                    manifest_file, ...
                    kemar_fs, ...
                    stim_set.fs, ...
                    kemar_stim, ...
                    "kemar", ...
                    target_distance_cm, ...
                    slowdown_factor, ...
                    "na", ...
                    "na", ...
                    "na", ...
                    "na", ...
                    target_azimuth_deg)
                for index = 1:length(stim_set.compensations)
                    compensation_descriptor = stim_set.compensations{index};
                    compensation_factor = resolve_compensation_factor( ...
                        slowdown_factor, compensation_descriptor);
                    if include_normal_orientation
                        orientation_indices = 1:2;
                    else
                        orientation_indices = 2:2;
                    end
                    for orientation_type_idx = orientation_indices
                        if orientation_type_idx == 1
                            orientation_type = "normal";
                            orientation_index = 9;
                        else
                            orientation_type = "matched";
                            key = slowdown_compensation_key( ...
                                slowdown_factor, ...
                                compensation_descriptor);
                            orientation_index = ild_matched_orientation_map(key);
                        end
                        stim = make_stim( ...
                            hrirs, ... 
                            fs, ...
                            ultrasound_pulse, ...
                            target_distance_cm / 100, ...
                            target_azimuth_deg, ...
                            slowdown_factor, ...
                            compensation_factor, ...
                            orientation_index);
                        click_stim = make_stim( ...
                            hrirs, ... 
                            fs, ...
                            click_pulse, ...
                            0, ...
                            target_azimuth_deg, ...
                            slowdown_factor, ...
                            compensation_factor, ...
                            orientation_index, ...
                            0);
                        save_single_stim( ...
                            target_directory, ...
                            manifest_file, ...
                            fs, ...
                            stim_set.fs, ...
                            stim, ...
                            "spherical", ...
                            target_distance_cm, ...
                            slowdown_factor, ...
                            compensation_factor, ...
                            compensation_descriptor, ...
                            orientation_type, ...
                            orientation_index, ...
                            target_azimuth_deg);
                       save_single_stim( ...
                            target_directory, ...
                            manifest_file, ...
                            fs, ...
                            stim_set.fs, ...
                            click_stim, ...
                            "click", ...
                            target_distance_cm, ...
                            slowdown_factor, ...
                            compensation_factor, ...
                            compensation_descriptor, ...
                            orientation_type, ...
                            orientation_index, ...
                            target_azimuth_deg);
                    end
                end
            end
        end
    end
end

function [pulse, click] = get_ultrasound_pulse_for_slowdown(stim_set, slowdown)
    arguments
        stim_set StimulusSet
        slowdown {mustBeNumeric}
    end
    pulse = Pulse( ...
        slowdown * stim_set.audible_chirp_frequency_band_hz(1), ...
        slowdown * stim_set.audible_chirp_frequency_band_hz(2), ...
        stim_set.pulse_length_s, ...
        stim_set.chirp_kind);
    click = Pulse(0, 0, 2 * stim_set.pulse_length_s, 'click');
end

function compensation_to_orientation_index = get_ild_matched_orientation_map( ...
    stim_set, ...
    hrirs, ...
    kemar_fs, ...
    kemar_hrirs)
    arguments
        stim_set StimulusSet
        hrirs (:,360,:)
        kemar_fs {mustBeNumeric}
        kemar_hrirs (73,2,:)
    end
    kemar_ild = get_kemar_ild(kemar_fs, kemar_hrirs, sort(stim_set.audible_chirp_frequency_band_hz));
    compensation_to_orientation_index = containers.Map();
    for slowdown = stim_set.slowdowns
      for index = 1:length(stim_set.compensations)
          compensation_descriptor = stim_set.compensations{index};
           key = slowdown_compensation_key(slowdown, compensation_descriptor);
           compensation = resolve_compensation_factor(slowdown, compensation_descriptor);
           ild_matched_orientation_index = get_ild_matched_orientation_for_compensation( ...
               hrirs, ...
               kemar_ild, ...
               compensation, ...
               false);
           compensation_to_orientation_index(key) = ild_matched_orientation_index;
      end
    end
end

function key = slowdown_compensation_key(slowdown, compensation)
    key = strcat(string(slowdown), "-", string(compensation));
end

function manifest_file = setup_manifest_file(parent_directory)
    manifest_file = strcat(parent_directory, filesep, "manifest.csv");
    handle = fopen(manifest_file, 'at');
    header = strjoin({ ...
        'filename', ...
        'model_name', ...
        'target_distance_cm', ...
        'slowdown', ...
        'compensation', ...
        'compensation_descriptor', ...
        'receiver_orientation_type', ...
        'receiver_orientation_index', ...
        'azimuth'}, ',');
    fprintf(handle, header);
end

function write_to_manifest_file( ...
    manifest_file, ...
    stim_file_name, ...
    model_name, ...
    target_distance_cm, ...
    slowdown, ...
    compensation, ...
    compensation_descriptor, ...
    receiver_orientation_type, ...
    receiver_orientation_index, ...
    azimuth)
    arguments
        manifest_file string
        stim_file_name string
        model_name string
        target_distance_cm {mustBeNumeric}
        slowdown {mustBeNumeric}
        compensation
        compensation_descriptor
        receiver_orientation_type string
        receiver_orientation_index
        azimuth {mustBeNumeric}
    end
    csv_row = sprintf( ...
        '\n%s,%s,%d,%d,%s,%s,%s,%s,%d', ...
        stim_file_name, ...
        model_name, ...
        target_distance_cm, ...
        slowdown, ...
        string(compensation), ...
        string(compensation_descriptor), ...
        receiver_orientation_type, ...
        string(receiver_orientation_index), ...
        azimuth);
    handle = fopen(manifest_file, 'at');
    fprintf(handle, csv_row);
end
    
function save_single_stim( ...
    parent_dir, ...
    manifest_file, ...
    fs, ...
    target_fs, ...
    stim, ...
    model_name, ...
    target_distance_cm, ...
    slowdown, ...
    compensation, ...
    compensation_descriptor, ...
    receiver_orientation_type, ...
    receiver_orientation_index, ...
    azimuth)
    arguments
        parent_dir string
        manifest_file string
        fs {mustBeNumeric}
        target_fs {mustBeNumeric}
        stim (2,:)
        model_name string
        target_distance_cm
        slowdown,
        compensation,
        compensation_descriptor
        receiver_orientation_type string,
        receiver_orientation_index,
        azimuth {mustBeNumeric}
    end
    if fs ~= target_fs
       stim = resample(stim', target_fs, fs)';
    end
    filename = strcat(model_name, "_", ... 
        string(target_distance_cm), "cm_", ...
        "s", string(slowdown), "_", ...
        "c", string(compensation), "_", ...
        "cd-", string(compensation_descriptor), "_", ...
        string(receiver_orientation_type), "_",...
        "a", string(azimuth), ".wav");
    qualified_path = strcat(parent_dir, filesep, filename);
    audiowrite(qualified_path, stim', target_fs);
    write_to_manifest_file( ...
        manifest_file, ...
        filename, ...
        model_name, ...
        target_distance_cm, ...
        slowdown, ...
        compensation, ...
        compensation_descriptor, ...
        receiver_orientation_type, ...
        receiver_orientation_index, ...
        azimuth);
end
    
