function stim_realtime = make_stim( ...
    hrirs, ... 
    fs, ...
    pulse, ...
    hrir_included_distance_m, ...
    target_distance_m, ...
    target_azimuth_deg, ...
    slowdown_factor, ...
    compensation_factor, ...
    orientation_index)
    arguments
        hrirs (:,:,:)
        fs {mustBeNumeric}
        pulse Pulse
        hrir_included_distance_m {mustBeNumeric}
        target_distance_m {mustBeNumeric}
        target_azimuth_deg {mustBeNumeric}
        slowdown_factor {mustBeNumeric}
        compensation_factor {mustBeNumeric}
        orientation_index {mustBeNumeric}
    end
    if target_distance_m < hrir_included_distance_m
        error("stim cannot be created at near-field distance");
    end
    echo_delay_s = (2 * target_distance_m - hrir_included_distance_m) / 343;
    [left_receiver_index, right_receiver_index] = get_receiver_indices(target_azimuth_deg, compensation_factor);
    [left_orientation_index, right_orientation_index] = get_orientation_indices(hrirs, orientation_index);
    stim_realtime = make_stim_from_hrirs( ...
        fs, ...
        squeeze(hrirs(left_orientation_index, left_receiver_index, :)), ...
        squeeze(hrirs(right_orientation_index, right_receiver_index, :)), ...
        pulse, ...
        echo_delay_s);
    stim = resample(stim_realtime', slowdown_factor, 1)';
    soundsc(stim, fs);
end