function stim = make_stim( ...
    hrirs, ... 
    fs, ...
    pulse, ...
    hrir_included_distance_m, ...
    target_distance_m, ...
    target_azimuth_deg, ...
    slowdown_factor, ...
    compensation_factor, ...
    orientation_index, ...
    play_sound)
    arguments
        hrirs (:,:,:)
        fs {mustBeNumeric}
        pulse Pulse
        hrir_included_distance_m {mustBeNumeric}
        target_distance_m {mustBeNumeric}
        target_azimuth_deg {mustBeNumeric}
        slowdown_factor {mustBeNumeric}
        compensation_factor {mustBeNumeric}
        orientation_index {mustBeNumeric}
        play_sound = true
    end
    if target_distance_m < hrir_included_distance_m
        error("stim cannot be created at near-field distance");
    end
    echo_delay_s = 2 * target_distance_m / 343;
    [left_hrir, right_hrir] = get_stereo_hrirs( ...
        hrirs, ...
        target_azimuth_deg, ...
        compensation_factor, ...
        orientation_index);
    stim_realtime = make_stim_from_hrirs( ...
        fs, ...
        left_hrir, ...
        right_hrir, ...
        pulse, ...
        echo_delay_s);
    stim = resample(stim_realtime', slowdown_factor, 1)';
    if play_sound
        soundsc(stim, fs);
    end
end